### ISSUE TITLE
Download failure

### ISSUE THREAD

**Issue by usherbob** [diegovalsesia/GraphCNN-GAN#1]
Hello Diego,
Thanks for sharing your code. It's really an excellent idea to use GAN in point cloud.
This repo is kind of large, which could easily lead to download failure. I tried three times and still failed. I think you can set up another repo without results.

**Comment by diegovalsesia** [comment]
I created a code-only repo at https://github.com/diegovalsesia/GraphCNN-GAN-codeonly

**Comment by usherbob** [comment]
Thanks.
