### ISSUE TITLE
Wrong Generation Results on Chair Class using the Pretrained Model

### ISSUE THREAD

**Issue by hughw19** [diegovalsesia/GraphCNN-GAN#2]
Hi Diego Valsesia,

Could you double-check the checkpoint you provide for generating chairs? I can only get weird outputs like below:
 
![image](https://user-images.githubusercontent.com/19866399/68838013-9986ad00-0672-11ea-975c-0049031ac2d7.png)

I can successfully generate point clouds for the other 3 classes. So, I believe the problem may be in the checkpoint for chair class.

Also, there is no training/test split information provided in this repo. Did you exactly follow r-GAN's data split or you have your own splitting?

A quick answer will be highly appreciated.

Best,
He

**Comment by diegovalsesia** [comment]
Fixed. Correct checkpoint is now available.
